FileVersion = 1

[Project]
Name = "hypatia-beef"
DefaultNamespace = "hypatia"

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
LibPaths = ["$(ProjectDir)\\libs\\windows\\hypatiad.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\hypatia.lib"]
