FileVersion = 1

[Project]
Name = "hypatia-beef"
DefaultNamespace = "hypatia"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\hypatia_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\hypatia.lib"]
